[package]
name = "advent-of-code-core"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.5"
strum = { version = "0.23.0", features = ["derive"] }
